name: Auto Update Clone

on:
  push:
    branches:
      - main  # Change this if your branch name is different

jobs:
  update_clone:
    runs-on: self-hosted  # Ensures it runs on your self-hosted runner

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Git Credentials
        run: |
          git config --global user.email "k213632@nu.edu.pk"
          git config --global user.name "lachman1"
          git config --global --unset http.https://github.com/.extraheader
          git config --global credential.helper cache

      - name: Set Permissions for Cloned Folder
        run: |
          sudo chown -R $USER:$USER /var/www/react-project
          sudo chmod -R 755 /var/www/react-project

      - name: Pull Latest Changes
        run: |
          cd /var/www/react-project
          git reset --hard
          git clean -fd
          git pull origin main  # Make sure 'main' is your correct branch

      - name: Restart Runner (if needed)
        run: |
          cd /var/www/react-project/actions-runner
          ./svc.sh stop || true
          ./svc.sh start
