name: Auto Update Clone

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  update_clone:
    runs-on: self-hosted  # Ensures it runs on your server

    steps:
      - name: Navigate to Cloned Folder
        run: cd /var/www/react-project

      - name: Set Git Credentials
        run: |
          git config --global user.email "k213632@nu.edu.pk"  # Correct email
          git config --global user.name "lachman1"  # Correct GitHub username
          git config --global --unset http.https://github.com/.extraheader
          git config --global credential.helper cache

      - name: Pull Latest Changes
        run: |
          cd /var/www/react-project
          git reset --hard
          git clean -fd
          git pull origin main  # Change 'main' if your branch is different

